volumes:
  postgres_volume:

services:
  pg:
    image: postgres:18.1-alpine3.22
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data


  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

  todo:
    build:
      context: .
      dockerfile: go.Dockerfile
    depends_on:
      - pg
    ports:
      - "7777:7777"
    environment:
      DB_HOST: pg
      DB_PORT: 5432

